/**
 * Canonical AI Hardware Accelerators Catalog
 * Sourced from official NVIDIA, Apple, AMD, and Intel technical whitepapers.
 */

export interface AiAccelerator {
  id: string;
  maker: "NVIDIA" | "Apple" | "AMD" | "Intel";
  name: string;
  category: "desktop" | "laptop" | "apple-silicon" | "workstation";
  memoryGiB: number;
  memoryKind: string;
  bandwidthGBs: number;
  runtimeSupport: ("CUDA" | "Metal" | "ROCm" | "Vulkan" | "CPU")[];
  powerEnvelopeWatts?: string;
  sourceUrl: string;
  badge?: string;
}

export const CANONICAL_AI_ACCELERATORS: AiAccelerator[] = [
  // ==================== NVIDIA RTX 50 & 40 SERIES (DESKTOP) ====================
  {
    id: "rtx-5090-32g",
    maker: "NVIDIA",
    name: "NVIDIA GeForce RTX 5090 (32GB)",
    category: "desktop",
    memoryGiB: 32,
    memoryKind: "GDDR7",
    bandwidthGBs: 1792,
    runtimeSupport: ["CUDA", "Vulkan"],
    powerEnvelopeWatts: "600 W",
    sourceUrl: "https://www.nvidia.com/en-us/geforce/graphics-cards/50-series/",
    badge: "Next-Gen Flagship",
  },
  {
    id: "rtx-5080-16g",
    maker: "NVIDIA",
    name: "NVIDIA GeForce RTX 5080 (16GB)",
    category: "desktop",
    memoryGiB: 16,
    memoryKind: "GDDR7",
    bandwidthGBs: 1024,
    runtimeSupport: ["CUDA", "Vulkan"],
    powerEnvelopeWatts: "400 W",
    sourceUrl: "https://www.nvidia.com/en-us/geforce/graphics-cards/50-series/",
    badge: "Fast GDDR7",
  },
  {
    id: "rtx-4090-24g",
    maker: "NVIDIA",
    name: "NVIDIA GeForce RTX 4090 (24GB)",
    category: "desktop",
    memoryGiB: 24,
    memoryKind: "GDDR6X",
    bandwidthGBs: 1008,
    runtimeSupport: ["CUDA", "Vulkan"],
    powerEnvelopeWatts: "450 W",
    sourceUrl: "https://www.nvidia.com/en-us/geforce/graphics-cards/40-series/rtx-4090/",
    badge: "Gold Standard Consumer AI",
  },
  {
    id: "rtx-4080-super-16g",
    maker: "NVIDIA",
    name: "NVIDIA GeForce RTX 4080 Super (16GB)",
    category: "desktop",
    memoryGiB: 16,
    memoryKind: "GDDR6X",
    bandwidthGBs: 736,
    runtimeSupport: ["CUDA", "Vulkan"],
    powerEnvelopeWatts: "320 W",
    sourceUrl: "https://www.nvidia.com/en-us/geforce/graphics-cards/40-series/rtx-4080-super/",
    badge: "High-End Desktop",
  },
  {
    id: "rtx-4070-ti-super-16g",
    maker: "NVIDIA",
    name: "NVIDIA GeForce RTX 4070 Ti Super (16GB)",
    category: "desktop",
    memoryGiB: 16,
    memoryKind: "GDDR6X",
    bandwidthGBs: 672,
    runtimeSupport: ["CUDA", "Vulkan"],
    powerEnvelopeWatts: "285 W",
    sourceUrl: "https://www.nvidia.com/en-us/geforce/graphics-cards/40-series/rtx-4070-ti-super/",
    badge: "Best Value 16GB AI",
  },
  {
    id: "rtx-4070-12g",
    maker: "NVIDIA",
    name: "NVIDIA GeForce RTX 4070 (12GB)",
    category: "desktop",
    memoryGiB: 12,
    memoryKind: "GDDR6X",
    bandwidthGBs: 504,
    runtimeSupport: ["CUDA", "Vulkan"],
    powerEnvelopeWatts: "200 W",
    sourceUrl: "https://www.nvidia.com/en-us/geforce/graphics-cards/40-series/rtx-4070/",
    badge: "Mid-Range Baseline",
  },
  {
    id: "rtx-4060-ti-16g",
    maker: "NVIDIA",
    name: "NVIDIA GeForce RTX 4060 Ti (16GB)",
    category: "desktop",
    memoryGiB: 16,
    memoryKind: "GDDR6",
    bandwidthGBs: 288,
    runtimeSupport: ["CUDA", "Vulkan"],
    powerEnvelopeWatts: "165 W",
    sourceUrl: "https://www.nvidia.com/en-us/geforce/graphics-cards/40-series/rtx-4060-ti/",
    badge: "Budget 16GB VRAM",
  },
  {
    id: "rtx-3090-24g",
    maker: "NVIDIA",
    name: "NVIDIA GeForce RTX 3090 (24GB)",
    category: "desktop",
    memoryGiB: 24,
    memoryKind: "GDDR6X",
    bandwidthGBs: 936,
    runtimeSupport: ["CUDA", "Vulkan"],
    powerEnvelopeWatts: "350 W",
    sourceUrl: "https://www.nvidia.com/en-us/geforce/graphics-cards/30-series/rtx-3090/",
    badge: "Used Market AI Hero",
  },

  // ==================== NVIDIA LAPTOP GPUS ====================
  {
    id: "rtx-4090-laptop-16g",
    maker: "NVIDIA",
    name: "NVIDIA RTX 4090 Laptop GPU (16GB)",
    category: "laptop",
    memoryGiB: 16,
    memoryKind: "GDDR6",
    bandwidthGBs: 576,
    runtimeSupport: ["CUDA", "Vulkan"],
    powerEnvelopeWatts: "150-175 W",
    sourceUrl: "https://www.nvidia.com/en-us/geforce/gaming-laptops/",
    badge: "Top Mobile GPU",
  },
  {
    id: "rtx-4080-laptop-12g",
    maker: "NVIDIA",
    name: "NVIDIA RTX 4080 Laptop GPU (12GB)",
    category: "laptop",
    memoryGiB: 12,
    memoryKind: "GDDR6",
    bandwidthGBs: 432,
    runtimeSupport: ["CUDA", "Vulkan"],
    powerEnvelopeWatts: "150 W",
    sourceUrl: "https://www.nvidia.com/en-us/geforce/gaming-laptops/",
  },
  {
    id: "rtx-4070-laptop-8g",
    maker: "NVIDIA",
    name: "NVIDIA RTX 4070 Laptop GPU (8GB)",
    category: "laptop",
    memoryGiB: 8,
    memoryKind: "GDDR6",
    bandwidthGBs: 256,
    runtimeSupport: ["CUDA", "Vulkan"],
    powerEnvelopeWatts: "105-140 W",
    sourceUrl: "https://www.nvidia.com/en-us/geforce/gaming-laptops/",
    badge: "Mainstream Gaming Laptop",
  },
  {
    id: "rtx-4060-laptop-8g",
    maker: "NVIDIA",
    name: "NVIDIA RTX 4060 Laptop GPU (8GB)",
    category: "laptop",
    memoryGiB: 8,
    memoryKind: "GDDR6",
    bandwidthGBs: 256,
    runtimeSupport: ["CUDA", "Vulkan"],
    powerEnvelopeWatts: "115 W",
    sourceUrl: "https://www.nvidia.com/en-us/geforce/gaming-laptops/",
  },

  // ==================== APPLE SILICON UNIFIED MEMORY ====================
  {
    id: "apple-m4-max-128g",
    maker: "Apple",
    name: "Apple M4 Max (128GB Unified Memory)",
    category: "apple-silicon",
    memoryGiB: 128,
    memoryKind: "Unified LPDDR5X",
    bandwidthGBs: 546,
    runtimeSupport: ["Metal"],
    powerEnvelopeWatts: "45-75 W",
    sourceUrl: "https://www.apple.com/macbook-pro/",
    badge: "Flagship Mac AI Workstation",
  },
  {
    id: "apple-m4-max-36g",
    maker: "Apple",
    name: "Apple M4 Max (36GB Unified Memory)",
    category: "apple-silicon",
    memoryGiB: 36,
    memoryKind: "Unified LPDDR5X",
    bandwidthGBs: 410,
    runtimeSupport: ["Metal"],
    powerEnvelopeWatts: "45 W",
    sourceUrl: "https://www.apple.com/macbook-pro/",
  },
  {
    id: "apple-m4-pro-48g",
    maker: "Apple",
    name: "Apple M4 Pro (48GB Unified Memory)",
    category: "apple-silicon",
    memoryGiB: 48,
    memoryKind: "Unified LPDDR5X",
    bandwidthGBs: 273,
    runtimeSupport: ["Metal"],
    powerEnvelopeWatts: "35 W",
    sourceUrl: "https://www.apple.com/macbook-pro/",
    badge: "Great 70B Quantized Runner",
  },
  {
    id: "apple-m3-max-36g",
    maker: "Apple",
    name: "Apple M3 Max (36GB Unified Memory)",
    category: "apple-silicon",
    memoryGiB: 36,
    memoryKind: "Unified LPDDR5",
    bandwidthGBs: 300,
    runtimeSupport: ["Metal"],
    powerEnvelopeWatts: "45 W",
    sourceUrl: "https://www.apple.com/macbook-pro/",
  },
  {
    id: "apple-m2-ultra-192g",
    maker: "Apple",
    name: "Apple M2 Ultra (192GB Unified Memory)",
    category: "apple-silicon",
    memoryGiB: 192,
    memoryKind: "Unified LPDDR5",
    bandwidthGBs: 800,
    runtimeSupport: ["Metal"],
    powerEnvelopeWatts: "100 W",
    sourceUrl: "https://www.apple.com/mac-studio/",
    badge: "Fits 70B/405B Full Offload",
  },
  {
    id: "apple-m2-ultra-128g",
    maker: "Apple",
    name: "Apple M2 Ultra (128GB Unified Memory)",
    category: "apple-silicon",
    memoryGiB: 128,
    memoryKind: "Unified LPDDR5",
    bandwidthGBs: 800,
    runtimeSupport: ["Metal"],
    powerEnvelopeWatts: "100 W",
    sourceUrl: "https://www.apple.com/mac-studio/",
  },
  {
    id: "apple-m2-max-32g",
    maker: "Apple",
    name: "Apple M2 Max (32GB Unified Memory)",
    category: "apple-silicon",
    memoryGiB: 32,
    memoryKind: "Unified LPDDR5",
    bandwidthGBs: 400,
    runtimeSupport: ["Metal"],
    powerEnvelopeWatts: "40 W",
    sourceUrl: "https://www.apple.com/macbook-pro/",
  },
  {
    id: "apple-m2-16g",
    maker: "Apple",
    name: "Apple M2 (16GB Unified Memory)",
    category: "apple-silicon",
    memoryGiB: 16,
    memoryKind: "Unified LPDDR5",
    bandwidthGBs: 100,
    runtimeSupport: ["Metal"],
    powerEnvelopeWatts: "15-20 W",
    sourceUrl: "https://www.apple.com/macbook-air/",
    badge: "Entry Unified Mac",
  },

  // ==================== AMD RADEON ====================
  {
    id: "amd-rx-7900-xtx-24g",
    maker: "AMD",
    name: "AMD Radeon RX 7900 XTX (24GB)",
    category: "desktop",
    memoryGiB: 24,
    memoryKind: "GDDR6",
    bandwidthGBs: 960,
    runtimeSupport: ["ROCm", "Vulkan"],
    powerEnvelopeWatts: "355 W",
    sourceUrl: "https://www.amd.com/en/products/graphics/amd-radeon-rx-7900xtx",
    badge: "24GB High-Bandwidth AMD",
  },
  {
    id: "amd-rx-7900-xt-20g",
    maker: "AMD",
    name: "AMD Radeon RX 7900 XT (20GB)",
    category: "desktop",
    memoryGiB: 20,
    memoryKind: "GDDR6",
    bandwidthGBs: 800,
    runtimeSupport: ["ROCm", "Vulkan"],
    powerEnvelopeWatts: "315 W",
    sourceUrl: "https://www.amd.com/en/products/graphics/amd-radeon-rx-7900xt",
  },

  // ==================== PRO WORKSTATION ACCELERATORS ====================
  {
    id: "rtx-pro-6000-blackwell-96g",
    maker: "NVIDIA",
    name: "NVIDIA RTX PRO 6000 Blackwell (96GB)",
    category: "workstation",
    memoryGiB: 96,
    memoryKind: "GDDR7 ECC",
    bandwidthGBs: 1792,
    runtimeSupport: ["CUDA", "Vulkan"],
    powerEnvelopeWatts: "600 W",
    sourceUrl: "https://www.nvidia.com/en-us/design-visualization/rtx-professional-workstations/",
    badge: "96GB Enterprise SOTA",
  },
  {
    id: "rtx-6000-ada-48g",
    maker: "NVIDIA",
    name: "NVIDIA RTX 6000 Ada Generation (48GB)",
    category: "workstation",
    memoryGiB: 48,
    memoryKind: "GDDR6 ECC",
    bandwidthGBs: 960,
    runtimeSupport: ["CUDA", "Vulkan"],
    powerEnvelopeWatts: "300 W",
    sourceUrl: "https://www.nvidia.com/en-us/design-visualization/rtx-6000/",
    badge: "48GB Pro Workstation",
  },
];
