/**
 * Comprehensive Canonical Open-Weight AI Models Catalog
 * Sourced directly from official publisher Hugging Face configuration files.
 */

export interface AiModelArchitecture {
  id: string;
  family: string;
  name: string;
  paramsB: number;
  activeParamsB?: number; // For MoE architectures
  architecture: "dense" | "moe" | "state-space";
  layers: number;
  hiddenSize: number;
  attentionHeads: number;
  kvHeads: number;
  headDim?: number;
  nativeContext: number;
  maxContext?: number;
  cacheType: "MHA" | "GQA" | "MLA" | "sliding" | "hybrid" | "state-space";
  mlaKvLoraRank?: number; // For DeepSeek MLA
  qkRopeHeadDim?: number;
  slidingWindow?: number; // For Mistral/Gemma
  globalAttentionEvery?: number;
  recurrentStateBytesPerLayer?: number; // For Mamba / RWKV
  vocabularySize?: number;
  sourceUrl: string;
  license: string;
  badge?: string;
}

export const CANONICAL_AI_MODELS: AiModelArchitecture[] = [
  // ==================== LLAMA 3.1 & 3.2 FAMILY ====================
  {
    id: "llama-3-2-1b",
    family: "Llama 3.2",
    name: "Llama 3.2 1B",
    paramsB: 1.23,
    architecture: "dense",
    layers: 16,
    hiddenSize: 2048,
    attentionHeads: 32,
    kvHeads: 8,
    nativeContext: 131072,
    cacheType: "GQA",
    sourceUrl: "https://huggingface.co/meta-llama/Llama-3.2-1B",
    license: "Llama 3.2 Community License",
    badge: "Ultra-Light / Mobile",
  },
  {
    id: "llama-3-2-3b",
    family: "Llama 3.2",
    name: "Llama 3.2 3B",
    paramsB: 3.21,
    architecture: "dense",
    layers: 28,
    hiddenSize: 3072,
    attentionHeads: 24,
    kvHeads: 8,
    nativeContext: 131072,
    cacheType: "GQA",
    sourceUrl: "https://huggingface.co/meta-llama/Llama-3.2-3B",
    license: "Llama 3.2 Community License",
    badge: "Fast Edge AI",
  },
  {
    id: "llama-3-1-8b",
    family: "Llama 3.1",
    name: "Llama 3.1 8B",
    paramsB: 8.03,
    architecture: "dense",
    layers: 32,
    hiddenSize: 4096,
    attentionHeads: 32,
    kvHeads: 8,
    nativeContext: 131072,
    cacheType: "GQA",
    sourceUrl: "https://huggingface.co/meta-llama/Llama-3.1-8B-Instruct",
    license: "Llama 3.1 Community License",
    badge: "Gold Standard Consumer",
  },
  {
    id: "llama-3-1-70b",
    family: "Llama 3.1",
    name: "Llama 3.1 70B",
    paramsB: 70.6,
    architecture: "dense",
    layers: 80,
    hiddenSize: 8192,
    attentionHeads: 64,
    kvHeads: 8,
    nativeContext: 131072,
    cacheType: "GQA",
    sourceUrl: "https://huggingface.co/meta-llama/Llama-3.1-70B-Instruct",
    license: "Llama 3.1 Community License",
    badge: "Workstation Grade",
  },
  {
    id: "llama-3-1-405b",
    family: "Llama 3.1",
    name: "Llama 3.1 405B",
    paramsB: 405.0,
    architecture: "dense",
    layers: 126,
    hiddenSize: 16384,
    attentionHeads: 128,
    kvHeads: 8,
    nativeContext: 131072,
    cacheType: "GQA",
    sourceUrl: "https://huggingface.co/meta-llama/Llama-3.1-405B-Instruct",
    license: "Llama 3.1 Community License",
    badge: "Enterprise Cluster",
  },

  // ==================== QWEN 2.5 FAMILY ====================
  {
    id: "qwen-2-5-1-5b",
    family: "Qwen 2.5",
    name: "Qwen 2.5 1.5B",
    paramsB: 1.54,
    architecture: "dense",
    layers: 28,
    hiddenSize: 1536,
    attentionHeads: 12,
    kvHeads: 2,
    nativeContext: 32768,
    cacheType: "GQA",
    sourceUrl: "https://huggingface.co/Qwen/Qwen2.5-1.5B-Instruct",
    license: "Apache-2.0",
    badge: "Coding Assistant Edge",
  },
  {
    id: "qwen-2-5-7b",
    family: "Qwen 2.5",
    name: "Qwen 2.5 7B",
    paramsB: 7.61,
    architecture: "dense",
    layers: 28,
    hiddenSize: 3584,
    attentionHeads: 28,
    kvHeads: 4,
    nativeContext: 131072,
    cacheType: "GQA",
    sourceUrl: "https://huggingface.co/Qwen/Qwen2.5-7B-Instruct",
    license: "Apache-2.0",
    badge: "Top 7B Performer",
  },
  {
    id: "qwen-2-5-14b",
    family: "Qwen 2.5",
    name: "Qwen 2.5 14B",
    paramsB: 14.7,
    architecture: "dense",
    layers: 48,
    hiddenSize: 5120,
    attentionHeads: 40,
    kvHeads: 8,
    nativeContext: 131072,
    cacheType: "GQA",
    sourceUrl: "https://huggingface.co/Qwen/Qwen2.5-14B-Instruct",
    license: "Apache-2.0",
    badge: "Sweet Spot Reasoning",
  },
  {
    id: "qwen-2-5-32b",
    family: "Qwen 2.5",
    name: "Qwen 2.5 32B",
    paramsB: 32.5,
    architecture: "dense",
    layers: 64,
    hiddenSize: 5120,
    attentionHeads: 40,
    kvHeads: 8,
    nativeContext: 131072,
    cacheType: "GQA",
    sourceUrl: "https://huggingface.co/Qwen/Qwen2.5-32B-Instruct",
    license: "Apache-2.0",
    badge: "Near 70B Reasoning",
  },
  {
    id: "qwen-2-5-72b",
    family: "Qwen 2.5",
    name: "Qwen 2.5 72B",
    paramsB: 72.7,
    architecture: "dense",
    layers: 80,
    hiddenSize: 8192,
    attentionHeads: 64,
    kvHeads: 8,
    nativeContext: 131072,
    cacheType: "GQA",
    sourceUrl: "https://huggingface.co/Qwen/Qwen2.5-72B-Instruct",
    license: "Qwen License",
    badge: "Flagship Open Source",
  },

  // ==================== DEEPSEEK REASONING (MLA & MoE) ====================
  {
    id: "deepseek-r1-distill-qwen-8b",
    family: "DeepSeek",
    name: "DeepSeek-R1-Distill-Qwen-8B",
    paramsB: 8.0,
    architecture: "dense",
    layers: 32,
    hiddenSize: 4096,
    attentionHeads: 32,
    kvHeads: 8,
    nativeContext: 131072,
    cacheType: "GQA",
    sourceUrl: "https://huggingface.co/deepseek-ai/DeepSeek-R1-Distill-Qwen-8B",
    license: "MIT",
    badge: "Top Local Reasoner",
  },
  {
    id: "deepseek-r1-distill-qwen-14b",
    family: "DeepSeek",
    name: "DeepSeek-R1-Distill-Qwen-14B",
    paramsB: 14.7,
    architecture: "dense",
    layers: 48,
    hiddenSize: 5120,
    attentionHeads: 40,
    kvHeads: 8,
    nativeContext: 131072,
    cacheType: "GQA",
    sourceUrl: "https://huggingface.co/deepseek-ai/DeepSeek-R1-Distill-Qwen-14B",
    license: "MIT",
    badge: "Powerful Math/Code",
  },
  {
    id: "deepseek-r1-distill-qwen-32b",
    family: "DeepSeek",
    name: "DeepSeek-R1-Distill-Qwen-32B",
    paramsB: 32.5,
    architecture: "dense",
    layers: 64,
    hiddenSize: 5120,
    attentionHeads: 40,
    kvHeads: 8,
    nativeContext: 131072,
    cacheType: "GQA",
    sourceUrl: "https://huggingface.co/deepseek-ai/DeepSeek-R1-Distill-Qwen-32B",
    license: "MIT",
    badge: "o1-Class Reasoning",
  },
  {
    id: "deepseek-v3-671b",
    family: "DeepSeek",
    name: "DeepSeek V3 / R1 (671B MoE)",
    paramsB: 671.0,
    activeParamsB: 37.0,
    architecture: "moe",
    layers: 61,
    hiddenSize: 7168,
    attentionHeads: 128,
    kvHeads: 128,
    nativeContext: 131072,
    cacheType: "MLA",
    mlaKvLoraRank: 512,
    qkRopeHeadDim: 64,
    sourceUrl: "https://huggingface.co/deepseek-ai/DeepSeek-R1",
    license: "MIT",
    badge: "Frontier SOTA (MLA)",
  },

  // ==================== MISTRAL & MIXTRAL ====================
  {
    id: "mistral-7b-v03",
    family: "Mistral",
    name: "Mistral 7B v0.3",
    paramsB: 7.25,
    architecture: "dense",
    layers: 32,
    hiddenSize: 4096,
    attentionHeads: 32,
    kvHeads: 8,
    nativeContext: 32768,
    cacheType: "sliding",
    slidingWindow: 4096,
    sourceUrl: "https://huggingface.co/mistralai/Mistral-7B-v0.3",
    license: "Apache-2.0",
    badge: "Proven Reliable",
  },
  {
    id: "mistral-nemo-12b",
    family: "Mistral",
    name: "Mistral NeMo 12B",
    paramsB: 12.2,
    architecture: "dense",
    layers: 40,
    hiddenSize: 5120,
    attentionHeads: 32,
    kvHeads: 8,
    nativeContext: 131072,
    cacheType: "GQA",
    sourceUrl: "https://huggingface.co/mistralai/Mistral-Nemo-Instruct-2407",
    license: "Apache-2.0",
    badge: "128k Native Context",
  },
  {
    id: "mixtral-8x7b",
    family: "Mistral",
    name: "Mixtral 8x7B (47B MoE)",
    paramsB: 46.7,
    activeParamsB: 12.9,
    architecture: "moe",
    layers: 32,
    hiddenSize: 4096,
    attentionHeads: 32,
    kvHeads: 8,
    nativeContext: 32768,
    cacheType: "sliding",
    slidingWindow: 4096,
    sourceUrl: "https://huggingface.co/mistralai/Mixtral-8x7B-Instruct-v0.1",
    license: "Apache-2.0",
    badge: "High Throughput MoE",
  },

  // ==================== GOOGLE GEMMA 2 ====================
  {
    id: "gemma-2-2b",
    family: "Gemma 2",
    name: "Gemma 2 2B",
    paramsB: 2.61,
    architecture: "dense",
    layers: 26,
    hiddenSize: 2304,
    attentionHeads: 8,
    kvHeads: 4,
    nativeContext: 8192,
    cacheType: "hybrid",
    slidingWindow: 4096,
    globalAttentionEvery: 2,
    sourceUrl: "https://huggingface.co/google/gemma-2-2b-it",
    license: "Gemma Terms of Use",
    badge: "Compact Mobile",
  },
  {
    id: "gemma-2-9b",
    family: "Gemma 2",
    name: "Gemma 2 9B",
    paramsB: 9.24,
    architecture: "dense",
    layers: 42,
    hiddenSize: 3584,
    attentionHeads: 16,
    kvHeads: 8,
    nativeContext: 8192,
    cacheType: "hybrid",
    slidingWindow: 4096,
    globalAttentionEvery: 2,
    sourceUrl: "https://huggingface.co/google/gemma-2-9b-it",
    license: "Gemma Terms of Use",
    badge: "Top Performer for 9B",
  },
  {
    id: "gemma-2-27b",
    family: "Gemma 2",
    name: "Gemma 2 27B",
    paramsB: 27.2,
    architecture: "dense",
    layers: 46,
    hiddenSize: 4608,
    attentionHeads: 32,
    kvHeads: 16,
    nativeContext: 8192,
    cacheType: "hybrid",
    slidingWindow: 4096,
    globalAttentionEvery: 2,
    sourceUrl: "https://huggingface.co/google/gemma-2-27b-it",
    license: "Gemma Terms of Use",
    badge: "High Accuracy",
  },

  // ==================== MICROSOFT PHI 3.5 ====================
  {
    id: "phi-3-5-mini",
    family: "Phi 3.5",
    name: "Phi 3.5 Mini (3.8B)",
    paramsB: 3.82,
    architecture: "dense",
    layers: 32,
    hiddenSize: 3072,
    attentionHeads: 32,
    kvHeads: 32,
    nativeContext: 131072,
    cacheType: "MHA",
    sourceUrl: "https://huggingface.co/microsoft/Phi-3.5-mini-instruct",
    license: "MIT",
    badge: "128k Long Context",
  },
  {
    id: "phi-3-5-moe",
    family: "Phi 3.5",
    name: "Phi 3.5 MoE (16x3.8B)",
    paramsB: 41.9,
    activeParamsB: 6.6,
    architecture: "moe",
    layers: 32,
    hiddenSize: 4096,
    attentionHeads: 32,
    kvHeads: 32,
    nativeContext: 131072,
    cacheType: "MHA",
    sourceUrl: "https://huggingface.co/microsoft/Phi-3.5-MoE-instruct",
    license: "MIT",
    badge: "Fast Reasoning MoE",
  },

  // ==================== STATE-SPACE / RECURRENT ====================
  {
    id: "mamba-2-8b",
    family: "State-Space",
    name: "Mamba 2.8B (Recurrent)",
    paramsB: 2.77,
    architecture: "state-space",
    layers: 64,
    hiddenSize: 2560,
    attentionHeads: 1,
    kvHeads: 1,
    nativeContext: 16384,
    cacheType: "state-space",
    recurrentStateBytesPerLayer: 5120,
    sourceUrl: "https://huggingface.co/state-spaces/mamba-2.8b",
    license: "Apache-2.0",
    badge: "Zero KV Cache Growth",
  },
];
