import { PersonaTemplate } from "@/lib/domain/needs-profile";

export const PERSONAS_CATALOG: PersonaTemplate[] = [
  {
    id: "persona-fullstack-dev",
    title: "Full-Stack Software Developer",
    category: "Development",
    description: "Multi-container backend development, frontend build tools, 30+ browser tabs, and local coding AI assistants.",
    badge: "Popular Preset",
    icon: "Code2",
    typicalWorkloads: [
      { softwareId: "soft-vscode", softwareName: "VS Code", intensity: "heavy", concurrencyGroup: "usually_together", quantity: 1, notes: "Multiple workspaces + Language Servers" },
      { softwareId: "soft-docker", softwareName: "Docker Desktop", intensity: "heavy", concurrencyGroup: "usually_together", quantity: 6, notes: "Postgres, Redis, 4x microservices" },
      { softwareId: "soft-chrome", softwareName: "Google Chrome", intensity: "heavy", concurrencyGroup: "usually_together", quantity: 1, notes: "30+ tabs, DevTools, React devtools" },
      { softwareId: "soft-postgres", softwareName: "PostgreSQL", intensity: "medium", concurrencyGroup: "usually_together", quantity: 1 },
      { softwareId: "soft-spotify", softwareName: "Spotify / Music", intensity: "light", concurrencyGroup: "usually_together", quantity: 1 },
      { softwareId: "soft-photoshop", softwareName: "Adobe Photoshop", intensity: "light", concurrencyGroup: "occasionally", quantity: 1, notes: "Occasional UI asset asset editing" },
    ],
    defaultAgentProfile: {
      llmModelId: "qwen2.5-coder-14b",
      modelName: "Qwen 2.5 Coder 14B Q4_K_M",
      quantization: "Q4_K_M",
      contextLengthTokens: 16384,
      concurrentAgents: 2,
      includesEmbeddingModel: true,
      includesVectorDb: true,
      includesDockerContainers: 4,
      includesBrowserAutomation: true,
      includesMcpToolServers: 3,
      executionPreference: "HYBRID_PREFERRED",
    },
    recommendedHardwareBaseline: {
      minRamGb: 32,
      recRamGb: 64,
      minVramGb: 8,
      recVramGb: 12,
      cpuCores: 8,
    },
    weights: {
      rawPerformance: 4,
      multitaskingMemory: 5,
      localAi: 4,
      gamingGraphics: 2,
      portabilityWeight: 3,
      batteryLife: 3,
      quietOperation: 4,
      upgradeability: 4,
      displayQuality: 4,
    },
  },
  {
    id: "persona-ai-builder",
    title: "AI Engineer & Agent Builder",
    category: "AI & ML",
    description: "Developing autonomous agent swarms, running local 14B–32B models, RAG vector pipelines, and fine-tuning experiments.",
    badge: "Heavy AI",
    icon: "Bot",
    typicalWorkloads: [
      { softwareId: "soft-vscode", softwareName: "VS Code / Cursor", intensity: "heavy", concurrencyGroup: "usually_together", quantity: 1 },
      { softwareId: "soft-ollama", softwareName: "Ollama / llama.cpp Server", intensity: "extreme", concurrencyGroup: "usually_together", quantity: 1 },
      { softwareId: "soft-docker", softwareName: "Docker (Qdrant, Chroma, MCP)", intensity: "heavy", concurrencyGroup: "usually_together", quantity: 4 },
      { softwareId: "soft-jupyter", softwareName: "Jupyter Lab / Python", intensity: "heavy", concurrencyGroup: "usually_together", quantity: 1 },
      { softwareId: "soft-chrome", softwareName: "Google Chrome", intensity: "heavy", concurrencyGroup: "usually_together", quantity: 1 },
    ],
    defaultAgentProfile: {
      llmModelId: "llama-3.1-8b-instruct",
      modelName: "Llama 3.1 8B Q8 / Qwen 14B Q4",
      quantization: "Q4_K_M",
      contextLengthTokens: 32768,
      concurrentAgents: 3,
      includesEmbeddingModel: true,
      includesVectorDb: true,
      includesDockerContainers: 6,
      includesBrowserAutomation: true,
      includesMcpToolServers: 5,
      executionPreference: "LOCAL_ONLY",
    },
    recommendedHardwareBaseline: {
      minRamGb: 32,
      recRamGb: 64,
      minVramGb: 12,
      recVramGb: 24,
      cpuCores: 12,
    },
    weights: {
      rawPerformance: 5,
      multitaskingMemory: 5,
      localAi: 5,
      gamingGraphics: 3,
      portabilityWeight: 2,
      batteryLife: 2,
      quietOperation: 3,
      upgradeability: 5,
      displayQuality: 4,
    },
  },
  {
    id: "persona-cs-student",
    title: "Computer Science Student",
    category: "Education",
    description: "University coursework, algorithms, Linux VMs/WSL, Android app projects, and lightweight local AI with 8+ hours battery.",
    badge: "Balanced & Portable",
    icon: "GraduationCap",
    typicalWorkloads: [
      { softwareId: "soft-vscode", softwareName: "VS Code", intensity: "medium", concurrencyGroup: "usually_together", quantity: 1 },
      { softwareId: "soft-chrome", softwareName: "Chrome (20 tabs + Canvas/PDF)", intensity: "medium", concurrencyGroup: "usually_together", quantity: 1 },
      { softwareId: "soft-android-studio", softwareName: "Android Studio", intensity: "heavy", concurrencyGroup: "occasionally", quantity: 1 },
      { softwareId: "soft-emulator", softwareName: "Android Emulator", intensity: "medium", concurrencyGroup: "occasionally", quantity: 1 },
      { softwareId: "soft-wsl", softwareName: "WSL2 / Ubuntu Linux VM", intensity: "medium", concurrencyGroup: "usually_together", quantity: 1 },
      { softwareId: "soft-light-gaming", softwareName: "Indie / Esports Gaming", intensity: "medium", concurrencyGroup: "never_together", quantity: 1 },
    ],
    defaultAgentProfile: {
      llmModelId: "qwen2.5-coder-7b",
      modelName: "Qwen 2.5 Coder 7B Q4",
      quantization: "Q4_K_M",
      contextLengthTokens: 8192,
      concurrentAgents: 1,
      includesEmbeddingModel: false,
      includesVectorDb: false,
      includesDockerContainers: 1,
      includesBrowserAutomation: false,
      includesMcpToolServers: 1,
      executionPreference: "HYBRID_PREFERRED",
    },
    recommendedHardwareBaseline: {
      minRamGb: 16,
      recRamGb: 32,
      minVramGb: 4,
      recVramGb: 8,
      cpuCores: 6,
    },
    weights: {
      rawPerformance: 3,
      multitaskingMemory: 4,
      localAi: 3,
      gamingGraphics: 2,
      portabilityWeight: 5,
      batteryLife: 5,
      quietOperation: 4,
      upgradeability: 3,
      displayQuality: 4,
    },
  },
  {
    id: "persona-mobile-dev",
    title: "Mobile App Developer (Flutter/React Native/Native)",
    category: "Development",
    description: "Simultaneous Android Studio, 2 active 1080p Virtual Devices, Xcode, Gradle build daemons, and browser testing.",
    badge: "Heavy RAM Load",
    icon: "Smartphone",
    typicalWorkloads: [
      { softwareId: "soft-android-studio", softwareName: "Android Studio / Xcode", intensity: "extreme", concurrencyGroup: "usually_together", quantity: 1 },
      { softwareId: "soft-emulator", softwareName: "Android Virtual Device", intensity: "heavy", concurrencyGroup: "usually_together", quantity: 2 },
      { softwareId: "soft-chrome", softwareName: "Chrome (25 tabs)", intensity: "medium", concurrencyGroup: "usually_together", quantity: 1 },
      { softwareId: "soft-vscode", softwareName: "VS Code", intensity: "medium", concurrencyGroup: "usually_together", quantity: 1 },
      { softwareId: "soft-figma", softwareName: "Figma Desktop", intensity: "medium", concurrencyGroup: "usually_together", quantity: 1 },
    ],
    recommendedHardwareBaseline: {
      minRamGb: 32,
      recRamGb: 48,
      minVramGb: 6,
      recVramGb: 8,
      cpuCores: 8,
    },
    weights: {
      rawPerformance: 4,
      multitaskingMemory: 5,
      localAi: 3,
      gamingGraphics: 2,
      portabilityWeight: 3,
      batteryLife: 4,
      quietOperation: 3,
      upgradeability: 4,
      displayQuality: 4,
    },
  },
  {
    id: "persona-video-editor",
    title: "Video Editor & Motion Designer",
    category: "Creative",
    description: "4K multi-stream timeline editing, After Effects complex motion graphics, and background Media Encoder export rendering.",
    badge: "GPU & VRAM Intensive",
    icon: "Video",
    typicalWorkloads: [
      { softwareId: "soft-premiere", softwareName: "Adobe Premiere Pro (4K timeline)", intensity: "extreme", concurrencyGroup: "usually_together", quantity: 1 },
      { softwareId: "soft-after-effects", softwareName: "Adobe After Effects (Motion Graphics)", intensity: "heavy", concurrencyGroup: "usually_together", quantity: 1 },
      { softwareId: "soft-media-encoder", softwareName: "Adobe Media Encoder", intensity: "heavy", concurrencyGroup: "usually_together", quantity: 1 },
      { softwareId: "soft-photoshop", softwareName: "Adobe Photoshop", intensity: "medium", concurrencyGroup: "occasionally", quantity: 1 },
    ],
    recommendedHardwareBaseline: {
      minRamGb: 32,
      recRamGb: 64,
      minVramGb: 8,
      recVramGb: 16,
      cpuCores: 8,
    },
    weights: {
      rawPerformance: 5,
      multitaskingMemory: 5,
      localAi: 2,
      gamingGraphics: 4,
      portabilityWeight: 2,
      batteryLife: 2,
      quietOperation: 3,
      upgradeability: 4,
      displayQuality: 5,
    },
  },
  {
    id: "persona-3d-artist",
    title: "3D Artist & Game Engine Developer",
    category: "Creative",
    description: "Blender Cycles realtime viewport, Unreal Engine 5 Nanite/Lumen level editing, high-poly sculpting, and GPU bake rendering.",
    badge: "Max GPU & VRAM",
    icon: "Box",
    typicalWorkloads: [
      { softwareId: "soft-blender", softwareName: "Blender 3D (Cycles/EEVEE)", intensity: "extreme", concurrencyGroup: "usually_together", quantity: 1 },
      { softwareId: "soft-unreal", softwareName: "Unreal Engine 5", intensity: "extreme", concurrencyGroup: "usually_together", quantity: 1 },
      { softwareId: "soft-substance", softwareName: "Substance 3D Painter", intensity: "heavy", concurrencyGroup: "occasionally", quantity: 1 },
      { softwareId: "soft-photoshop", softwareName: "Photoshop (8K Textures)", intensity: "heavy", concurrencyGroup: "occasionally", quantity: 1 },
    ],
    recommendedHardwareBaseline: {
      minRamGb: 32,
      recRamGb: 64,
      minVramGb: 12,
      recVramGb: 24,
      cpuCores: 12,
    },
    weights: {
      rawPerformance: 5,
      multitaskingMemory: 5,
      localAi: 3,
      gamingGraphics: 5,
      portabilityWeight: 1,
      batteryLife: 1,
      quietOperation: 2,
      upgradeability: 5,
      displayQuality: 5,
    },
  },
];
